# -*- coding: utf-8 -*-
"""lec4_hw4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Geib8q-UxKHq9XhIbGlA2HT6ivHb_GF

## Homework 4

+ 학번: 22102001
+ 이름: 신지혜

제출방법:
+ 1) github에 본인 repository를 만들고, 작성한 소스 코드를 upload 하세요.
+ 2) 출력 결과는 캡처하여 README.md에 첨부하세요.
+ 3) 자신의 github README.md 화면을 캡쳐하여 과제에 제출하세요.

### Exercise 1. 노래 가사 파일에서 단어 `"Yesterday"`의 **개수**를 세는 프로그램을 작성하세요.

### tips:
- .upper(), .lower(), .count(),
"""

# 파일을 불러옵니다.
with open('yesterday.txt', 'r') as f:
    yesterday_lyric = f.read()

yesterday_lyric

# TODO: Your code here

count = yesterday_lyric.lower().count("yesterday")

print("Yesterday 개수:", count)

"""## Excercise 2. Yesterday 노래엔 `Yesterday` 라는 말이 몇번나올까?

+ 대소문자를 구분하여 `Yesterday`와 `yesterday`의 개수를 나눠서 세는 프로그램을 작성하세요.
+ (정규표현식 `re` package 쓰지 말 것)

+ tips
    + .replace(), .split(), count()
"""

# TODO: Your code here


print("Yesterday 개수:", yesterday_lyric.count("Yesterday"))
print("yesterday 개수:", yesterday_lyric.count("yesterday"))